[package]
name = "rit-15"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.57", features = ["derive"] }
flate2 = "1.1.9"
hex = "0.4.3"
sha1 = "0.10.6"
thiserror = "2.0.18"
walkdir = "2.5.0"
