[package]
name = "simple-webscraper-09"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.55", features = ["derive"] }
reqwest = "0.13.1"
scraper = "0.25.0"
tokio = { version = "1.49.0", features = ["full"] }
